export const SET_APP_LANGUAGE = 'SET_APP_LANGUAGE';

// USER SESSION
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNIN_RESPONSE = 'SIGNIN_RESPONSE';
export const SIGNUP_RESPONSE = 'SIGNUP_RESPONSE';
export const SET_USER = 'SET_USER';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_PROFILEIMAGE = 'SET_PROFILEIMAGE';
export const SET_PREFERENCE = 'SET_PREFERENCE';
export const USER_SESSION_CHANGE_STATE = 'USER_SESSION_CHANGE_STATE';
export const PREFERRED_INDUSTRY = 'PREFERRED_INDUSTRY';
export const PREFERRED_JOB_TYPE = 'PREFERRED_JOB_TYPE'
export const SELECTEDSCREEN = 'SELECTEDSCREEN'
export const LANDINGTOPROFILE = 'LANDINGTOPROFILE'
export const SCREENNAME = 'SCREENNAME'
export const FCMTOKEN = 'FCMTOKEN'
export const ALLPHONECONTACTS = 'ALLPHONECONTACTS'
export const PAYPALLIVE = 'PAYPALLIVE'


// LOGOUT 
export const LOGOUT = 'LOGOUT'